### ISSUE TITLE
Add "compile" and "render" functions to Environment

### ISSUE THREAD

**Issue by vkottler** [vkottler/datazen#3]
Once these exist, run some existing (or new) "compile" and "render" commands through the environment as a front-end.

The arguments to these functions should inform how a manifest could be targeted to perform the invocation (as if it's a Makefile) and possibly how a dependency relationship can be formed between them (also as if it's a Makefile).

**Comment by vkottler** [comment]
We may want / need to re-evaluate what's required in a manifest and what's not. Possibly we just want a manifest to hold these compile and render definitions and the schemas for those elements should probably be able to specify their own directories, so that you can persist with just one monolithic manifest (if you choose).

Probably we just want something like:

```
job_name:
  configs:
  - "optional"
  variables:
  - "optional"
  templates:
  - "optional"
  schemas:
  - "optional"
  depends_on:
  - "job_name_a"
  - "job_name_b" # should order matter for these or should it be reasonable to build them in parallel?
  command: "render" # or "compile"
    arg1: "test"
    arg2: "test"
```

**Comment by vkottler** [comment]
The manifest schema should possibly just be in code, so that it's easier to build a complex relationship between elements.

**Comment by vkottler** [comment]
We may need a "noop" command to support "phony" targets.

**Comment by vkottler** [comment]
Determining updates required could get complicated fast, `make`'s strategy of using file timestamps is good but we may want to try something like checksums on the dependencies, or a combination of both where some kind of "audit" can make sure the timestamp strategy is still working, and if not update our cache of information.

**Comment by vkottler** [comment]
Made some progress on this:

```
configs:
  type: list
  schema:
    type: "string"

schemas:
  type: list
  schema:
    type: "string"

templates:
  type: list
  schema:
    type: "string"

variables:
  type: list
  schema:
    type: "string"

compiles:
  type: list
  schema:
    type: "dict"
    schema:
      name:
        type: "string"
      b:
        type: "string"
      c:
        type: "string"

renders:
  type: list
  schema:
    type: "dict"
    schema:
      name:
        type: "string"
      b:
        type: "string"
      c:
        type: "string"
```

Compiling and rendering need to be able to specify directories, additive to the ones optionally provided above.

Need to settle on an initial set of arguments / front-end for these schemas. From there, we can perform the invocation to the underlying "compile" or "render".

We can probably get rid of `cmd_compile` and `cmd_render` at some point, too. Maybe worth keeping them though
